# Generated by Django 5.1.3 on 2024-11-26 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(choices=[(1, 'Urgent'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=4, max_length=6)),
                ('visibility', models.CharField(choices=[('P', 'Public'), ('R', 'Private')], default='R', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['publish_date'], name='Task_task_publish_d02ddc_idx')],
            },
        ),
    ]
