# Generated by Django 5.1.3 on 2024-11-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Urgent'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=4, max_length=10),
        ),
    ]
